# Generated by Django 2.2.27 on 2022-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puestos', models.IntegerField(max_length=200, verbose_name='Numero de puestos')),
                ('puestos_con_gerentes', models.IntegerField(verbose_name='Numero de puestos con gerentes')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservacion',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo corporativo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombres')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de reserva')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuario',
            },
        ),
    ]
