# Generated by Django 4.1 on 2022-09-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_area_usuarios_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='reservacion',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Reservacion', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='puestos_con_gerentes',
        ),
        migrations.AddField(
            model_name='reservacion',
            name='dias',
            field=models.CharField(default='', max_length=200, verbose_name='Días de la semana'),
        ),
    ]
